<footer style="padding:1rem;background:#f3f3f3;margin-top:2rem">
    <div style="max-width:900px;margin:0 auto;color:#333;font-size:0.9rem">
        <p>Generated by project scaffold. Edit templates/header.php and templates/footer.php for layout.</p>
    </div>
</footer>
<script>
// expose CSRF token for JS usage
window.__CSRF_TOKEN__ = '<?= \Core\Csrf::token() ?>';
</script>
<script src="/assets/js/sortable.js"></script>
</body>
</html>
